import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin,AiFillInstagram,AiFillGithub} from 'react-icons/ai'
import Image from "next/image"
import Profile from "../public/Profile.png"
import project_1 from "../public/project-1.jpg"
import project_2 from "../public/project-2.png"
import project_3 from "../public/project-3.jpg"
import { useState } from 'react'



export default function Home() {
  const [darkMode,setDarkMode] = useState(false)
  return (
    <div className={darkMode?"dark":""}>
      <Head>
        <title>Antro Safin</title>
        <meta name="description" content="Generated by create next app" />
        <link  rel="shortcut icon" href="favicon.png" />
      </Head>

      <main className='bg-zinc-200 px-10 pb-1 mx-auto md:px-20 lg:px-40 dark:bg-gray-900'>
        {/* Section 1 */}
        <section className='min-h-screen font-burtons'>

          {/* Navigations */}
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl dark:text-white'>
              Antro 
            </h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-xl dark:text-white'/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          {/* Navigations */}

          {/* Profile */}
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden'>
            <Image src={Profile} layout="fill" objectFit='cover' />
          </div>
          {/* Profile */}

          {/* About */}
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Antro Safin</h2>
            <h3 className='text-2xl py-2 font-medium dark:text-white'>Software Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-zinc-300'>I am currently pursuing my graduation in B.Tech Information Technology.</p>
          </div>
          {/* About */}

          {/* Social Links */}
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-zinc-300'>
            <a href="https://www.linkedin.com/in/antro-safin-m"><AiFillLinkedin /></a>
            <a href='https://github.com/AntroSafin'><AiFillGithub /></a>
            <a href='https://www.instagram.com/antro_safin'><AiFillInstagram /></a>
          </div>
          {/* Social Links */}

        </section>
        {/* Section 1 */}

        <div className='h-1 bg-gradient-to-l from-teal-500 my-10'></div>

        {/* Section 2 */}
        <section>
          <div className='text-center p-10 font-burtons'>
            <h3 className='text-4xl font-medium dark:text-white'>Projects</h3>
          </div>

          <div className='font-cascadia'>
            {/* Project 1 */}
            <div className='text-center shadow-xl shadow-teal-600/60 p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={project_1} width={200} height={200} />
              <h3 className='text-xl font-medium pt-8 pb-4'><a href='https://github.com/AntroSafin/GiphySearch' className='bg-gradient-to-r from-teal-400 to-cyan-500 text-white px-4 py-2 rounded-full'>AirCnc_FrontEnd</a></h3>
              <p className='py-2'>
                This is the Frontend design of the dog rent website created with the guide given by onemonth learning site.
              </p>
              <h4 className='py-4 text-teal-600'>Tools and Languages Used:</h4>
              <p className='text-gray-800 py-1'>Html</p>
              <p className='text-gray-800 py-1'>Css</p>
            </div>
            {/* Project 1 */}

            {/* Project 2 */}
            <div className='text-center shadow-xl shadow-teal-600/60 p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={project_2} width={200} height={200} />
              <h3 className='text-xl font-medium pt-8 pb-4'><a href='https://github.com/AntroSafin/GiphySearch' className='bg-gradient-to-r from-teal-400 to-cyan-500 text-white px-4 py-2 rounded-full'>GiphySearch</a></h3>
              <p className='py-2'>
                A simple Website which search for gif images.
              </p>
              <p className='py-2'>
                I used the Giphy API for getting gif from the Giphy Site.
              </p>
              <h4 className='py-4 text-teal-600'>Tools and Languages Used:</h4>
              <p className='text-gray-800 py-1'>Html</p>
              <p className='text-gray-800 py-1'>Css</p>
              <p className='text-gray-800 py-1'>JavaScript</p>
            </div>
            {/* Project 2 */}

            {/* Project 3 */}
            <div className='text-center shadow-xl shadow-teal-600/60 p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={project_3} width={200} height={200} />
              <h3 className='text-xl font-medium pt-8 pb-4'><a href='https://github.com/AntroSafin/GiphySearch' className='bg-gradient-to-r from-teal-400 to-cyan-500 text-white px-4 py-2 rounded-full'>ChatBot</a></h3>
              <p className='py-2'>
                Simple ChatBot for Banking FAQ answers.
              </p>
              <p className='py-2'>
                We used AIML which is the extension of XML for this project.
              </p>
              <p className='py-2'>
                The language we learnt and used are JSP and AIML.
              </p>
              <h4 className='py-4 text-teal-600'>Tools and Languages Used:</h4>
              <p className='text-gray-800 py-1'>JSP</p>
              <p className='text-gray-800 py-1'>Java</p>
              <p className='text-gray-800 py-1'>AIML</p>
              <p className='text-gray-800 py-1'>Eclipse</p>
            </div>
            {/* Project 3 */}

          </div>
        </section>
        {/* Section 2 */}
      </main>
    </div>
  )
}
